### ISSUE TITLE
issue about the preprocess

### ISSUE THREAD

**Issue by isakhuang** [johnPertoft/noise-to-noise#2]
hi, John,
     Nice to meet you!
     I try your code and it work well. excellent!
     I wonder where do you do the normalization of the input? I can't find the part to convert input to 0-1. 
In noise.py line 29:
    "return add_noise(img, stddev1), add_noise(img, stddev2)"
as I see the img range (0-255) and the stddev1 range (0-1),  it's really weird.
    Thank you!

**Comment by johnPertoft** [comment]
Hi, thanks for using it!

The clean images are normalized to [0, 1] on [this line](https://github.com/johnPertoft/noise2noise/blob/master/n2n/data/dataset.py#L15). Furthermore the paper mentioned sampling the stddev for the additive gaussian noise distribution from [0, 50] indicating they assumed img range [0, 255] which is why I scaled the sampled stddev down.

**Comment by isakhuang** [comment]
Nice.....
this function's name is not really abvious -_-||
thank you very much!
