### ISSUE TITLE
Is there a way to use existing Watermark overlay noised images to train noise model(aim to remove watermark)? 

### ISSUE THREAD

**Issue by ghost** [johnPertoft/noise-to-noise#3]
I want to remove image or video watermark.
In your method, we must split noise model before train a model.
But it's difficult to split text(watermark) noise model because the watermark is already on images.
So is there a way to use existing watermarked images to train a model?

Thanks!

**Comment by johnPertoft** [comment]
Sounds like the problem is the same as the text overlay noise? Unless I'm misunderstanding you.

In either case, this model requires each training data pair (input and target image) to consist of two noisy examples of the same image. In your case you can probably just generate this by overlaying the watermark at some random location in the image, once for the input image and once for the target image.
